version: 2
updates:
  - package-ecosystem: "npm" # Checks for npm/pnpm updates
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*" 
  
  - package-ecosystem: "github-actions" # Keep the CI/CD pipelines compliant and secure
    directory: "/"
    schedule:
      interval: "weekly"
